### ISSUE TITLE
Add LiteSpeed option

### ISSUE THREAD

**Issue by joejordanbrown** [tripflex/cpsetup#13]
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cpanel:auto-installer

```
wget http://www.litespeedtech.com/packages/cpanel/lsws_whm_autoinstaller.sh
bash lsws_whm_autoinstaller.sh $LITESPEED_SERIAL 2 0 $LITESPEED_UN $LITESPEED_PW $LITESPEED_EMAIL 1 1
rm -rf lsws_whm_autoinstaller.sh
```

**Comment by tripflex** [comment]
Closing this as EasyApache4 now has this built-in: 

https://documentation.cpanel.net/display/CKB/How+to+Purchase+a+LiteSpeed+Web+Server+License
